spring:
  main:
    log-startup-info: true # логирование деталей старта разрешено
    banner-mode: CONSOLE

    # настраиваем уровень логера
logging.level:
 root: INFO
 ru.yandex.practicum.quiz.QuizApp: TRACE
 ru.yandex.practicum.quiz: TRACE


spring-quiz:
  report:
    mode: "concise"